version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
- x64
- Win32
before_build:
- cmd: premake5.exe vs2017
build:
  project: OpenParrot.sln
  verbosity: minimal
after_build:
  7z a OpenParrotTest.zip build\x64\*.dll build\x64\*.exe build\Win32\*.dll build\Win32\*.exe
artifacts:
- path: build\bin\release\
  name: OpenParrot$(platform)
deploy:
- provider: GitHub
  release: OpenParrot$(platform)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: a2B+6mDTHuBa0fw8nm739eGJIZBcZp0IenhKvvXvreLR6ZUoHg9pflMP8ahNUK6o
  repository: teknogods/OpenParrot
  artifact: OpenParrot$(platform).zip