version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
# Do not build on tags (GitHub only)
skip_tags: true
platform:
- x64
- Win32
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: premake5.exe vs2017
- ps: >-
    Get-Content .\OpenParrot\src\OpenParrot.rc | ForEach-Object { $_ -replace "1.0.0.0", $env:appveyor_build_version } | Set-Content .\OpenParrot\src\OpenParrot2.rc
    
    del .\OpenParrot\src\OpenParrot.rc
    
    mv .\OpenParrot\src\OpenParrot.rc .\OpenParrot\src\OpenParrot.rc
    
build:
  project: OpenParrot.sln
  verbosity: minimal

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: build\bin\release\output\
  name: OpenParrot$(platform)
deploy:
- provider: GitHub
  release: OpenParrot$(platform)_$(APPVEYOR_BUILD_VERSION)
  tag: OpenParrot$(platform)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: a2B+6mDTHuBa0fw8nm739eGJIZBcZp0IenhKvvXvreLR6ZUoHg9pflMP8ahNUK6o
  repository: teknogods/OpenParrot
  artifact: build\bin\release\OpenParrot$(platform).zip
  force_update: true
